import Layout from "@/components/Layout";
import { capitalizedWords } from "@/components/Reuse";
import "@/styles/globals.css";
import "@/styles/login.css";
import Head from "next/head";
import { useRouter } from "next/router";

export default function App({ Component, pageProps }) {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>
          Swop Admin -
          {capitalizedWords(router.pathname.split("/")[1] || "Dashboard")}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}
