import EmailSupport from "@/components/EmailSupport";
import LiveSupport from "@/components/LiveSupport";
import ProblemSolve from "@/components/ProblemSolve";
import Sidebar from "@/components/Sidebar";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { MdOutlineGraphicEq, MdOutlineEmail } from "react-icons/md";
import { VscTools } from "react-icons/vsc";

const Supports = () => {
  const [page, setPage] = useState("live-support");

  return (
    <>
      <Head>
        <title>Swop Admin - Support</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="main-container">
          <Sidebar />
          <div className="main-content">
            <div className="home-top-panel-out">
              <div className="home-top-panel">
                <h2>Dashboard</h2>
                <input type="text" placeholder="🔎︎ Search here..." />
                <select className="select-language">
                  <option value="eng">Eng (US)</option>
                  <option value="eng">Eng (US)</option>
                </select>
                <div className="travis-card">
                  <Image
                    src="/image/travis.png"
                    alt="travis_image"
                    height={54}
                    width={55}
                    className="travis_image"
                  />
                  <p>Travis Herron</p>
                </div>
              </div>
            </div>
            <div className="container">
              <div className="support-top-btn">
                <div
                  className="support-live-support"
                  onClick={() => setPage("live-support")}
                >
                  <MdOutlineGraphicEq size={20} />
                  <p>Live Support</p>
                </div>
                <div
                  className="support-email-support"
                  onClick={() => setPage("email-support")}
                >
                  <MdOutlineEmail size={20} />
                  <p>Email Support</p>
                </div>
                <div
                  className="support-problem-solve"
                  onClick={() => setPage("problem-solve")}
                >
                  <VscTools size={20} />
                  <p>Problem Solve</p>
                </div>
              </div>
              <div className="support-top-btn">
                <div className="support-border-out">
                  <div
                    className={`${
                      page === "live-support" && "div-boder-color-change"
                    }`}
                  />
                </div>
                <div className="support-border-out">
                  <div
                    className={`${
                      page === "email-support" && "div-boder-color-change"
                    }`}
                  />
                </div>
                <div className="support-border-out">
                  <div
                    className={`${
                      page === "problem-solve" && "div-boder-color-change"
                    }`}
                  />
                </div>
              </div>
              {page === "live-support" && <LiveSupport />}
              {page === "email-support" && <EmailSupport />}
              {page === "problem-solve" && <ProblemSolve />}
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Supports;
